; generated by GEOBENCH iconedit (24x21 px)
copy_w           equ   6            ; width in packed bytes (24px)
copy_h           equ   21            ; height in rows
copy
                db    #0F,#0F,#0F,#0F,#0F,#0F
                db    #0F,#0F,#0F,#0F,#0F,#0F
                db    #1E,#F0,#F0,#F0,#0F,#0F
                db    #1E,#F0,#F0,#F0,#0F,#0F
                db    #1E,#87,#0F,#3C,#0F,#0F
                db    #1E,#87,#0F,#3C,#0F,#0F
                db    #1E,#87,#0F,#3C,#0F,#0F
                db    #1E,#87,#F0,#F0,#F0,#C3
                db    #1E,#87,#F0,#F0,#F0,#C3
                db    #1E,#87,#C3,#3C,#0F,#C3
                db    #1E,#87,#C3,#3C,#0F,#C3
                db    #1E,#87,#C3,#3C,#0F,#C3
                db    #1E,#87,#C3,#3C,#0F,#C3
                db    #1E,#F0,#F0,#F0,#0F,#C3
                db    #1E,#F0,#F0,#F0,#0F,#C3
                db    #0F,#0F,#C3,#0F,#0F,#C3
                db    #0F,#0F,#C3,#0F,#0F,#C3
                db    #0F,#0F,#C3,#0F,#0F,#C3
                db    #0F,#0F,#F0,#F0,#F0,#C3
                db    #0F,#0F,#F0,#F0,#F0,#C3
                db    #0F,#0F,#0F,#0F,#0F,#0F
