#!/usr/bin/env python3
import sys
from pathlib import Path


def check_amsdos_name(name: str) -> str:
    if "." not in name:
        raise ValueError(f"DSK name must be 8.3: {name}")
    stem, ext = name.split(".", 1)
    if not stem or not ext or len(stem) > 8 or len(ext) > 3:
        raise ValueError(f"DSK name must be 8.3: {name}")
    return name.upper()


def main() -> int:
    if len(sys.argv) < 4:
        print("usage: mk_dsk_pack.py OUT_DIR OUT_DSK NAME=PATH ...", file=sys.stderr)
        return 2

    out_dir = Path(sys.argv[1])
    out_dsk = Path(sys.argv[2]).resolve()
    entries = []
    for spec in sys.argv[3:]:
        if "=" not in spec:
            print(f"bad entry: {spec}", file=sys.stderr)
            return 2
        raw_name, path = spec.split("=", 1)
        try:
            name = check_amsdos_name(raw_name)
        except ValueError as exc:
            print(exc, file=sys.stderr)
            return 2
        entries.append((name, Path(path).resolve()))

    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.asm"):
        old.unlink()

    for i, (name, path) in enumerate(entries):
        lines = [
            ";; Generated by tools/mk_dsk_pack.py - do not edit.",
            "                org   #4000",
            f"file_start      incbin \"{path}\"",
            "file_end",
            f"                save  \"{name}\",file_start,file_end-file_start,DSK,\"{out_dsk}\"",
        ]
        asm_name = f"{i:02d}_{name.replace('.', '_')}.asm"
        (out_dir / asm_name).write_text("\n".join(lines) + "\n", encoding="ascii")

    (out_dir / ".stamp").write_text("\n".join(name for name, _ in entries) + "\n", encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
